name: Python distributions

on: [push, pull_request]

jobs:
  build-wheels:
    name: Build wheel
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.7]
        os: [windows-latest]
        python-arch: [x86, x64]

    steps:
      - uses: actions/checkout@v1

      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          python-architecture: ${{ matrix.python-arch }}

      - name: Install dependencies
        env:
          PIP_EXTRA_INDEX_URL: "http://pypi.naturalcapitalproject.org/simple/"
          PIP_TRUSTED_HOST: "pypi.naturalcapitalproject.org"
          PIP_PREFER_BINARY: 1
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
          python setup.py install

      - name: Build wheel
        shell: cmd
        run: |
          python setup.py --version > python-version.txt
          setx /P VERSION=< python-version.txt
          python setup.py bdist_wheel
          dir dist > wheel_name.txt
          setx /P WHEEL_PATH=< wheel_name.txt

      - name: Upload built wheel
        uses: actions/upload-artifact@v1
        with:
          name: Wheel for ${{ matrix.os }} python ${{ matrix.python-version }} ${{ matrix.python-arch }}
          path: ${{ env.WHEEL_PATH }}

  build-sdist:
    name: Build sdist
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v1

      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          python-architecture: x64

      - name: Install dependencies
        run: pip install numpy cython setuptools_scm

      - name: Build sdist
        shell: cmd
        run: |
          python setup.py --version > python-version.txt
          setx /P VERSION=< python-version.txt
          echo ${{ env.VERSION }}
          python setup.py sdist --formats=zip

      - name: Check version string
        shell: cmd
        run: echo ${{ env.VERSION }}

      - name: Upload built sdist
        uses: actions/upload-artifact@v1
        with:
          name: Source distribution
          path: dist/pygeoprocessing-${{ env.VERSION }}.zip
